-- =====================================================================
-- Digital Heroes — core schema, security (RLS) and business rules
-- Run in: Supabase Dashboard > SQL Editor > New query > paste > Run
-- All money is stored in PAISE (integer) to avoid floating-point errors.
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------- Enums ----------------------------------------------------
create type user_role           as enum ('user', 'admin');
create type plan_interval       as enum ('monthly', 'yearly');
create type subscription_status as enum ('incomplete', 'active', 'past_due', 'cancelled', 'expired');
create type draw_type           as enum ('random', 'algorithmic');
create type draw_status         as enum ('draft', 'simulated', 'published');
create type verification_status as enum ('awaiting_proof', 'pending_review', 'approved', 'rejected');
create type payment_status      as enum ('pending', 'paid');

-- ---------- Global settings (single row, admin-tunable) --------------
create table app_settings (
  id                     boolean primary key default true check (id),   -- enforces single row
  monthly_price_paise    int  not null default 49900,    -- ₹499
  yearly_price_paise     int  not null default 499900,   -- ₹4,999 (~17% discount)
  prize_pool_percent     int  not null default 50 check (prize_pool_percent between 0 and 90),
  min_charity_percent    int  not null default 10 check (min_charity_percent between 0 and 100),
  updated_at             timestamptz not null default now()
);
insert into app_settings default values;

-- ---------- Charities ------------------------------------------------
create table charities (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  slug         text not null unique,
  category     text not null default 'General',
  short_desc   text not null default '',
  description  text not null default '',
  image_url    text,
  is_featured  boolean not null default false,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now()
);

create table charity_events (
  id          uuid primary key default gen_random_uuid(),
  charity_id  uuid not null references charities(id) on delete cascade,
  title       text not null,
  event_date  date not null,
  location    text,
  created_at  timestamptz not null default now()
);
create index on charity_events (charity_id, event_date);

-- ---------- Profiles (1:1 with auth.users) ---------------------------
create table profiles (
  id               uuid primary key references auth.users(id) on delete cascade,
  email            text not null,
  full_name        text not null default '',
  role             user_role not null default 'user',
  charity_id       uuid references charities(id) on delete set null,
  charity_percent  int  not null default 10 check (charity_percent between 10 and 100),
  created_at       timestamptz not null default now()
);

-- ---------- Subscriptions (written ONLY by the server / payment-provider webhook) -----------
create table subscriptions (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null references profiles(id) on delete cascade,
  plan                     plan_interval not null,
  status                   subscription_status not null default 'incomplete',
  amount_paise             int  not null,
  provider_customer_id       text,
  provider_subscription_id   text unique,
  current_period_end       timestamptz,
  cancel_at_period_end     boolean not null default false,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index on subscriptions (user_id, status);

-- Ledger of charity money generated by each successful payment
create table charity_contributions (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references profiles(id) on delete cascade,
  charity_id       uuid references charities(id) on delete set null,
  subscription_id  uuid references subscriptions(id) on delete set null,
  amount_paise     int  not null check (amount_paise >= 0),
  percent_applied  int  not null,
  provider_payment_id text unique,           -- idempotency: one row per invoice
  created_at       timestamptz not null default now()
);
create index on charity_contributions (user_id);
create index on charity_contributions (charity_id);

-- Independent, one-off donations (not tied to gameplay)
create table donations (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid references profiles(id) on delete set null,
  charity_id         uuid not null references charities(id),
  amount_paise       int  not null check (amount_paise >= 10000),   -- min ₹100
  provider_payment_id  text unique,
  created_at         timestamptz not null default now()
);

-- ---------- Scores ---------------------------------------------------
create table scores (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references profiles(id) on delete cascade,
  score       int  not null check (score between 1 and 45),          -- Stableford
  played_on   date not null,
  created_at  timestamptz not null default now(),
  unique (user_id, played_on)                                        -- one score per date
);
create index on scores (user_id, played_on desc);

-- ---------- Draws ----------------------------------------------------
create table draws (
  id                    uuid primary key default gen_random_uuid(),
  draw_month            date not null unique,                 -- always 1st of month
  draw_type             draw_type not null default 'random',
  status                draw_status not null default 'draft',
  winning_numbers       int[] ,                                -- 5 numbers, 1..45
  active_subscribers    int  not null default 0,
  prize_pool_paise      int  not null default 0,               -- this month's fresh pool
  jackpot_carry_paise   int  not null default 0,               -- rolled over from previous draw
  pool_5_paise          int  not null default 0,               -- includes carry
  pool_4_paise          int  not null default 0,
  pool_3_paise          int  not null default 0,
  jackpot_rolled_over   boolean not null default false,        -- true if nobody hit 5
  simulation            jsonb,                                 -- last simulation preview payload
  published_at          timestamptz,
  created_at            timestamptz not null default now(),
  check (extract(day from draw_month) = 1)
);

-- Snapshot of each participant's scores at draw time (auditable)
create table draw_entries (
  id            uuid primary key default gen_random_uuid(),
  draw_id       uuid not null references draws(id) on delete cascade,
  user_id       uuid not null references profiles(id) on delete cascade,
  scores        int[] not null,
  match_count   int  not null default 0 check (match_count between 0 and 5),
  unique (draw_id, user_id)
);
create index on draw_entries (user_id);

-- ---------- Winners (verification + payout) --------------------------
create table winners (
  id                  uuid primary key default gen_random_uuid(),
  draw_id             uuid not null references draws(id) on delete cascade,
  draw_entry_id       uuid not null references draw_entries(id) on delete cascade,
  user_id             uuid not null references profiles(id) on delete cascade,
  match_tier          int  not null check (match_tier in (3, 4, 5)),
  prize_paise         int  not null check (prize_paise >= 0),
  verification        verification_status not null default 'awaiting_proof',
  payment             payment_status not null default 'pending',
  proof_path          text,                                    -- storage path in 'winner-proofs'
  admin_note          text,
  reviewed_at         timestamptz,
  paid_at             timestamptz,
  created_at          timestamptz not null default now(),
  unique (draw_id, user_id),
  check (payment = 'pending' or verification = 'approved')     -- can't pay unverified winners
);
create index on winners (user_id);

-- =====================================================================
-- Helper functions (SECURITY DEFINER so RLS policies can call them)
-- =====================================================================
create or replace function is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = auth.uid() and role = 'admin');
$$;

-- Real-time entitlement check used by RLS and the app on every request
create or replace function has_active_subscription(uid uuid default auth.uid()) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from subscriptions
    where user_id = uid and status = 'active'
      and (current_period_end is null or current_period_end > now())
  );
$$;

-- =====================================================================
-- Triggers
-- =====================================================================

-- Create profile automatically on signup (charity chosen at signup)
create or replace function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_charity uuid;
  v_pct int;
begin
  select id into v_charity from charities
   where id::text = new.raw_user_meta_data->>'charity_id' and is_active;
  v_pct := greatest(
    (select min_charity_percent from app_settings),
    coalesce(nullif(new.raw_user_meta_data->>'charity_percent', '')::int, 10)
  );
  insert into profiles (id, email, full_name, charity_id, charity_percent)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''), v_charity, least(v_pct, 100));
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users for each row execute function handle_new_user();

-- Prevent privilege escalation: only an admin (or service role) can change role
create or replace function protect_profile_role() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.role is distinct from old.role and auth.uid() is not null and not is_admin() then
    raise exception 'You are not allowed to change roles.';
  end if;
  return new;
end $$;

create trigger profiles_protect_role
  before update on profiles for each row execute function protect_profile_role();

-- Score rules: not in the future; a new score must be newer than the oldest of 5
create or replace function validate_score() returns trigger
language plpgsql as $$
declare cnt int; oldest date;
begin
  if new.played_on > (now() at time zone 'Asia/Kolkata')::date then
    raise exception 'The date cannot be in the future.';
  end if;
  if tg_op = 'INSERT' then
    select count(*), min(played_on) into cnt, oldest from scores where user_id = new.user_id;
    if cnt >= 5 and new.played_on < oldest then
      raise exception 'That date is older than your 5 most recent scores. Edit an existing score instead.';
    end if;
  end if;
  return new;
end $$;

create trigger scores_validate
  before insert or update on scores for each row execute function validate_score();

-- Rolling window: keep only the latest 5 (newest date first); oldest is dropped
create or replace function trim_scores() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  delete from scores where id in (
    select id from scores where user_id = new.user_id
    order by played_on desc, created_at desc offset 5
  );
  return null;
end $$;

create trigger scores_trim
  after insert on scores for each row execute function trim_scores();

-- Winner proof submission: users can ONLY set their own proof via this function
create or replace function submit_winner_proof(p_winner_id uuid, p_path text) returns void
language plpgsql security definer set search_path = public as $$
begin
  update winners
     set proof_path = p_path, verification = 'pending_review', admin_note = null
   where id = p_winner_id and user_id = auth.uid()
     and verification in ('awaiting_proof', 'rejected');
  if not found then
    raise exception 'This prize cannot accept a proof upload right now.';
  end if;
end $$;

-- =====================================================================
-- Row Level Security
-- =====================================================================
alter table app_settings           enable row level security;
alter table charities              enable row level security;
alter table charity_events         enable row level security;
alter table profiles               enable row level security;
alter table subscriptions          enable row level security;
alter table charity_contributions  enable row level security;
alter table donations              enable row level security;
alter table scores                 enable row level security;
alter table draws                  enable row level security;
alter table draw_entries           enable row level security;
alter table winners                enable row level security;

-- settings: anyone reads (pricing page), admin edits
create policy settings_read  on app_settings for select using (true);
create policy settings_admin on app_settings for update using (is_admin()) with check (is_admin());

-- charities: public directory, admin CRUD
create policy charities_read  on charities for select using (is_active or is_admin());
create policy charities_admin on charities for all using (is_admin()) with check (is_admin());
create policy events_read     on charity_events for select using (true);
create policy events_admin    on charity_events for all using (is_admin()) with check (is_admin());

-- profiles: own row (role change blocked by trigger) + admin
create policy profiles_self_read   on profiles for select using (id = auth.uid() or is_admin());
create policy profiles_self_update on profiles for update using (id = auth.uid() or is_admin());

-- subscriptions / contributions / donations: read own; writes via service role only
create policy subs_read   on subscriptions         for select using (user_id = auth.uid() or is_admin());
create policy subs_admin  on subscriptions         for update using (is_admin());
create policy contrib_read on charity_contributions for select using (user_id = auth.uid() or is_admin());
create policy donations_read on donations           for select using (user_id = auth.uid() or is_admin());

-- scores: users manage own scores ONLY while subscribed; admin manages all
create policy scores_read   on scores for select using (user_id = auth.uid() or is_admin());
create policy scores_insert on scores for insert with check (
  (user_id = auth.uid() and has_active_subscription()) or is_admin());
create policy scores_update on scores for update using (
  (user_id = auth.uid() and has_active_subscription()) or is_admin());
create policy scores_delete on scores for delete using (
  (user_id = auth.uid() and has_active_subscription()) or is_admin());

-- draws: published draws are public (landing page "latest draw"); admin sees all
create policy draws_read  on draws for select using (status = 'published' or is_admin());
create policy draws_admin on draws for all using (is_admin()) with check (is_admin());

-- entries / winners: users see only their own, and only for published draws
create policy entries_read on draw_entries for select using (
  is_admin() or (user_id = auth.uid() and exists (select 1 from draws d where d.id = draw_id and d.status = 'published')));
create policy entries_admin on draw_entries for all using (is_admin()) with check (is_admin());
create policy winners_read  on winners for select using (user_id = auth.uid() or is_admin());
create policy winners_admin on winners for all using (is_admin()) with check (is_admin());

-- =====================================================================
-- Storage buckets
-- =====================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('winner-proofs', 'winner-proofs', false, 5242880, array['image/png','image/jpeg','image/webp'])
on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('charity-media', 'charity-media', true, 5242880, array['image/png','image/jpeg','image/webp'])
on conflict (id) do nothing;

-- Proofs live at  {user_id}/{filename}. Users write only inside their own folder.
create policy proofs_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'winner-proofs' and (storage.foldername(name))[1] = auth.uid()::text);
create policy proofs_read on storage.objects for select to authenticated
  using (bucket_id = 'winner-proofs' and ((storage.foldername(name))[1] = auth.uid()::text or is_admin()));

create policy media_read  on storage.objects for select using (bucket_id = 'charity-media');
create policy media_admin on storage.objects for all to authenticated
  using (bucket_id = 'charity-media' and is_admin()) with check (bucket_id = 'charity-media' and is_admin());
